// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.jarvis.rediscache.protobuf;

public final class ReportPB {
  private ReportPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ReportBean extends
      com.google.protobuf.GeneratedMessage {
    // Use ReportBean.newBuilder() to construct.
    private ReportBean() {}
    
    private static final ReportBean defaultInstance = new ReportBean();
    public static ReportBean getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReportBean getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jarvis.rediscache.protobuf.ReportPB.internal_static_com_jarvis_rediscache_protobuf_ReportBean_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jarvis.rediscache.protobuf.ReportPB.internal_static_com_jarvis_rediscache_protobuf_ReportBean_fieldAccessorTable;
    }
    
    // required string taskId = 1;
    public static final int TASKID_FIELD_NUMBER = 1;
    private boolean hasTaskId;
    private java.lang.String taskId_ = "";
    public boolean hasTaskId() { return hasTaskId; }
    public java.lang.String getTaskId() { return taskId_; }
    
    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private boolean hasStatus;
    private int status_ = 0;
    public boolean hasStatus() { return hasStatus; }
    public int getStatus() { return status_; }
    
    // required string message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    // required int64 reportTime = 4;
    public static final int REPORTTIME_FIELD_NUMBER = 4;
    private boolean hasReportTime;
    private long reportTime_ = 0L;
    public boolean hasReportTime() { return hasReportTime; }
    public long getReportTime() { return reportTime_; }
    
    public final boolean isInitialized() {
      if (!hasTaskId) return false;
      if (!hasStatus) return false;
      if (!hasMessage) return false;
      if (!hasReportTime) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTaskId()) {
        output.writeString(1, getTaskId());
      }
      if (hasStatus()) {
        output.writeInt32(2, getStatus());
      }
      if (hasMessage()) {
        output.writeString(3, getMessage());
      }
      if (hasReportTime()) {
        output.writeInt64(4, getReportTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTaskId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTaskId());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getStatus());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMessage());
      }
      if (hasReportTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getReportTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jarvis.rediscache.protobuf.ReportPB.ReportBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jarvis.rediscache.protobuf.ReportPB.ReportBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.jarvis.rediscache.protobuf.ReportPB.ReportBean result;
      
      // Construct using com.jarvis.rediscache.protobuf.ReportPB.ReportBean.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.jarvis.rediscache.protobuf.ReportPB.ReportBean();
        return builder;
      }
      
      protected com.jarvis.rediscache.protobuf.ReportPB.ReportBean internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.jarvis.rediscache.protobuf.ReportPB.ReportBean();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jarvis.rediscache.protobuf.ReportPB.ReportBean.getDescriptor();
      }
      
      public com.jarvis.rediscache.protobuf.ReportPB.ReportBean getDefaultInstanceForType() {
        return com.jarvis.rediscache.protobuf.ReportPB.ReportBean.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.jarvis.rediscache.protobuf.ReportPB.ReportBean build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.jarvis.rediscache.protobuf.ReportPB.ReportBean buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.jarvis.rediscache.protobuf.ReportPB.ReportBean buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.jarvis.rediscache.protobuf.ReportPB.ReportBean returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jarvis.rediscache.protobuf.ReportPB.ReportBean) {
          return mergeFrom((com.jarvis.rediscache.protobuf.ReportPB.ReportBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jarvis.rediscache.protobuf.ReportPB.ReportBean other) {
        if (other == com.jarvis.rediscache.protobuf.ReportPB.ReportBean.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasReportTime()) {
          setReportTime(other.getReportTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTaskId(input.readString());
              break;
            }
            case 16: {
              setStatus(input.readInt32());
              break;
            }
            case 26: {
              setMessage(input.readString());
              break;
            }
            case 32: {
              setReportTime(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required string taskId = 1;
      public boolean hasTaskId() {
        return result.hasTaskId();
      }
      public java.lang.String getTaskId() {
        return result.getTaskId();
      }
      public Builder setTaskId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTaskId = true;
        result.taskId_ = value;
        return this;
      }
      public Builder clearTaskId() {
        result.hasTaskId = false;
        result.taskId_ = getDefaultInstance().getTaskId();
        return this;
      }
      
      // required int32 status = 2;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public int getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(int value) {
        result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = 0;
        return this;
      }
      
      // required string message = 3;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // required int64 reportTime = 4;
      public boolean hasReportTime() {
        return result.hasReportTime();
      }
      public long getReportTime() {
        return result.getReportTime();
      }
      public Builder setReportTime(long value) {
        result.hasReportTime = true;
        result.reportTime_ = value;
        return this;
      }
      public Builder clearReportTime() {
        result.hasReportTime = false;
        result.reportTime_ = 0L;
        return this;
      }
    }
    
    static {
      com.jarvis.rediscache.protobuf.ReportPB.getDescriptor();
    }
    
    static {
      com.jarvis.rediscache.protobuf.ReportPB.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvis_rediscache_protobuf_ReportBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jarvis_rediscache_protobuf_ReportBean_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016reportPB.proto\022\036com.jarvis.rediscache." +
      "protobuf\"Q\n\nReportBean\022\016\n\006taskId\030\001 \002(\t\022\016" +
      "\n\006status\030\002 \002(\005\022\017\n\007message\030\003 \002(\t\022\022\n\nrepor" +
      "tTime\030\004 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_jarvis_rediscache_protobuf_ReportBean_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_jarvis_rediscache_protobuf_ReportBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jarvis_rediscache_protobuf_ReportBean_descriptor,
              new java.lang.String[] { "TaskId", "Status", "Message", "ReportTime", },
              com.jarvis.rediscache.protobuf.ReportPB.ReportBean.class,
              com.jarvis.rediscache.protobuf.ReportPB.ReportBean.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
